### ISSUE TITLE
you are appending the fieldset here, but the "[ ]" brackets appear to be missing in the target string?

### ISSUE THREAD

**Issue by simonmittag** [sypht-team/sypht-ruby-client#1]
https://github.com/sypht-team/sypht-ruby-client/blob/0351ebfe815cfd2d06ba9862a5351ba3d8bf58d8/lib/sypht/client.rb#L94

**Comment by rush-skills** [comment]
Since this is a Ruby Array, append inserts this string into the array, which when sent as a JSON POST request gets converted to `["item1","item2"]` format
